# Generated by Django 5.2.5 on 2025-11-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('average_likelihood', models.FloatField(default=0.0)),
                ('at_risk_students', models.IntegerField(default=0)),
                ('likely_to_pass', models.IntegerField(default=0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('feature_importance', models.JSONField(default=dict)),
                ('model_performance', models.JSONField(default=dict)),
                ('user_statistics', models.JSONField(default=dict)),
                ('trend_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistic',
                'verbose_name_plural': 'Dashboard Statistics',
                'db_table': 'dashboard_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_predictions', models.IntegerField(default=0)),
                ('average_probability', models.FloatField(default=0.0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Trend',
                'verbose_name_plural': 'Monthly Trends',
                'db_table': 'monthly_trends',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
